### ISSUE TITLE
[COSMETIC] Name for tab

### ISSUE THREAD

**Issue by jirikolacia** [dclaramount/shootingRange#16]
Within Správa rezervací, please change name from "Události" for tab události to "Nastavení", thank you ;)

![image](https://github.com/user-attachments/assets/469db166-112f-45d8-a83c-d96c0f89e839)

**Comment by dclaramount** [comment]
Label updated!!!!
![Screenshot 2024-12-09 at 18 13 10](https://github.com/user-attachments/assets/02f69a20-0b97-44a4-9e26-7009e24e3ffb)
